CREATE TABLE PROFESOR (
    DNI VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(35) NOT NULL,
    APELLIDO VARCHAR(35) NOT NULL,
    APELLIDO2 VARCHAR(35),
    DIRECCION VARCHAR(35) NOT NULL,
    CUENTA VARCHAR(35) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    CONSTRAINT PK_PROFESOR PRIMARY KEY(DNI)
);

CREATE TABLE CICLO (
    COD_CICLO NUMBER(3) NOT NULL,
    NOMBRE VARCHAR(35) NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    CONSTRAINT PK_CILCO PRIMARY KEY(COD_CICLO)
);

CREATE TABLE ASIGNATURA (
    COD_ASIG NUMBER(3) NOT NULL,
    NOMBRE VARCHAR(35) NOT NULL,
    NUM_HORAS NUMBER(3) NOT NULL,
    DNI VARCHAR(9) NOT NULL,
    COD_CICLO NUMBER(3) NOT NULL,
    CONSTRAINT FK_PROFESOR FOREIGN KEY(DNI) REFERENCES PROFESOR(),
    CONSTRAINT FK_CICLOFORM FOREIGN KEY(CODCICLO) REFERENCES CICLO(),
);

CREATE TABLE IDIOMA (
    COD_IDIOMA NUMBER(3) NOT NULL,
    DESCRIPCION VARCHAR(40) NOT NULL,
    CONSTRAINT PK_IDIOMA PRIMARY KEY(COD_IDIOMA)
);

CREATE TABLE ALUMNO (
    DNI VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(35) NOT NULL,
    APELLIDO(35) NOT NULL,
    APELLIDO2 VARCHAR(35),
    DIRECCION VARCHAR(35) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    COD_IDIOMA NUMBER(3) NOT NULL,
    CONSTRAINT PK_ALUMNO FOREIGN KEY (DNI),
    CONSTRAINT FK_IDIOMA FOREIGN KEY (COD_IDIOMA)
);

CREATE TABLE MATRICULA (
    DNI VARCHAR(9) NOT NULL,
    COD_ASIG NUMBER(3) NOT NULL,
    CONSTRAINT PK_MATRICULA PRIMARY KEY(DNI) REFERENCES ALUMNO(),
    CONSTRAINT PK_MATRICULA PRIMARY KEY(COD_ASIG) REFERENCES MATRICULA(),
);

CREATE TABLE IDIOMASPROF (
    COD_IDIOMA NUMBER(3) NOT NULL,
    DNI VARCHAR(9) NOT NULL,
    CONSTRAINT PK_IDIOMASPROF PRIMARY KEY(COD_IDIOMA) REFERENCES IDIOMA(),
    CONSTRAINT PK_IDIOMASPROF PRIMARY KEY(DNI) REFERENCES PROFESOR(),
);