CREATE TABLE FABRICANTE (
    CODFAB NUMBER(3) NOT NULL,
    FABRICANTE VARCHAR(30) NOT NULL,
    CONSTRAINT PK_FABRICANTE PRIMARY KEY(CODFAB)
);

CREATE TABLE MARCA (
    CODMARCA NUMBER(3) NOT NULL,
    MARCA VARCHAR(30) NOT NULL,
    CONSTRAINT PK_MARCA PRIMARY KEY(CODMARCA)
);

CREATE TABLE VEHICULO (
    CODVEH VARCHAR(7) NOT NULL,
    MODELO VARCHAR(10) NOT NULL,
    TIPO VARCHAR(10) NOT NULL,
    COLOR VARCHAR(10) NOT NULL,
    CODFAB NUMBER(3) NOT NULL,
    CODMARCA NUMBER(3) NOT NULL,
    CONSTRAINT PK_VEHICULO PRIMARY KEY(CODVEH),
    CONSTRAINT FK_CODFAB FOREIGN KEY(CODFAB) REFERENCES FABRICANTE(),
    CONSTRAINT FK_CODMARCA FOREIGN KEY(CODMARCA) REFERENCES MARCA()
);

CREATE TABLE CLIENTE (
    DNI VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO1 VARCHAR(30) NOT NULL,
    APELLIDO2 VARCHAR(30),
    DOMICILIO VARCHAR(30) NOT NULL,
    NUMTARJETA VARCHAR(30) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(DNI),
);

CREATE TABLE EMPLEADO (
    DNI VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO1 VARCHAR(30) NOT NULL,
    APELLIDO2 VARCHAR(30),
    DOMICILIO VARCHAR(30) NOT NULL,
    NUMCUENTA NUMBER(30) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(DNI),
);

CREATE TABLE CURSO (
    CODCURSO NUMBER(3) NOT NULL,
    DESCRIPCION VARCHAR(30) NOT NULL,
    NUMHORAS NUMBER(3) NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT PK_CURSO PRIMARY KEY(DNI)
);

CREATE TABLE CURSOEMPL (
    CODCURSO NUMBER(3) NOT NULL,
    DNI VARCHAR(9) NOT NULL,
    CONSTRAINT PK_CURSOEMPL PRIMARY KEY(CODCURSO) REFERENCES CURSO(),
    CONSTRAINT PK_CURSOEMPL PRIMARY KEY(DNI) REFERENCES EMPLEADO(),
);

CREATE TABLE ALQUILER (
    CODALQUILER NUMBER(3) NOT NULL,
    FEHCA DATE NOT NULL,
    NUMDIAS NUMBER(3) NOT NULL,
    KMACTUAL NUMBER(5) NOT NULL,
    KMENTREGA NUMBER(5) NOT NULL,
    CODVEH VARCHAR(7) NOT NULL,
    DNI VARHCAR(9) NOT NULL,
    DNI VARHCAR(9) NOT NULL,
    CONSTRAINT PK_ALQUILER PRIMARY KEY(CODALQUILER),
    CONSTRAINT FK_ALQUILER FOREIGN KEY(CODVEH) REFERENCES VEHICULO(),
    CONSTRAINT FK_ALQUILER FOREIGN KEY(DNI) REFERENCES CLIENTE(),
    CONSTRAINT FK_ALQUILER FOREIGN KEY(DNI) REFERENCES EMPLEADO(),
);

CREATE TABLE OFICINA (
    CODOFICINA NUMBER(3) NOT NULL,
    DOMICILIO VARCHAR(30) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    CONSTRAINT PK_OFICINA PRIMARY KEY(CODOFICINA) REFERENCES OFICINA(),
    CONSTRAINT PK_CODALQUILER PRIMARY KEY(CODALQUILER) REFERENCES ALQUILER(),
);

CREATE TABLE OFICINAALQ (
    CODOFICINA NUMBER(3) NOT NULL,
    CODALQUILER NUMBER(3) NOT NULL,
    CONSTRAINT FK_OFICINA FOREIGN KEY(CODOFICINA) REFERENCES OFICINA(),
    CONSTRAINT FK_CODALQUILER FOREIGN KEY(CODALQUILER) REFERENCES ALQUILER(),
);